### ISSUE TITLE
Error: Cannot find module 'pnpm-logger'

### ISSUE THREAD

**Issue by vjpr** [pnpm/supi#13]
I got this error when trying to include `supi`. `pnpm-logger` is listed as devDep.

**Comment by zkochan** [comment]
It is a peer dependency, your project should rely on it as well. There is a note about it in the Installation section

**Comment by vjpr** [comment]
Its a peer dep and a devDep. Is that valid - is it how npm and yarn handle it?

I didn't receive any warning about it - perhaps because it is listed as both.

**Comment by zkochan** [comment]
It is a devDep for local development. I don't know why you did not receive any warnings. What pm have you used?

It should be a peer dep because the logger should be a singleton and only installed in pnpm or some other package that uses supi

**Comment by vjpr** [comment]
Just tried again and I did receive warnings. Closing.
